### PR TITLE
Image support.

### PR DESCRIPTION
**Pull request by millette**
Implements #2.

### CODE REVIEW

**Comment by millette** [comment]
I'm no git pro, and I didn't pay attention to your indentation format and had to fix that in a few commits. There's probably some squashing or rebase magic that escapes me, but at least the feature is there :-)

**Comment by aranciaga** [comment]
Good! but postStatusImage function seems not working, can you check this?

**Comment by aranciaga** [comment]
I said nothing, everything is perfect! I think some servers require content-length header, but is not necessary to add, because if not require that header, will return bad request error.

**Comment by aranciaga** [comment]
By the way, congratulations! it's a very good patch. Thanks a lot :)

**Pull request merged**
